project:
  type: website
  resources: 
    -"*.jpeg"
  
website:
  title: "Kwiz Computing Technologies"
  page-navigation: true
  cookie-consent: false
  
  navbar:
    foreground: "#1c4c9c"
    logo: 'images/Kwiz Logo Symbol 2400x1800.jpg'
    logo-alt: "Kwiz Computing Technologies"
    
    right:
      - text: "Home"
        href: index.qmd
        
      - text: "Resource Centre"
        href: resources.qmd
        
      - text: "Demos"
        href: demos.qmd

  search: 
    location: navbar
    type: textbox  

    
  page-footer: 
    background: "#ad9882"
    foreground: "#1c4c9c"
    
    left: '&#169;2023: Kwiz Computing Technologies'
    right: 
      - icon: github
        href: https://github.com/Kwiz-Computing-Technologies-Limited
      - icon: linkedin
        href: https://www.linkedin.com/company/kwizresearch/

  
        

format:
  html:
    theme: sandstone
    backgroundcolor: "#ffffff"
    mainfont: Black Street
    fontcolor: black
    linkcolor: "#104898"
    
    page-layout: full
    css: styles.css
    toc: false
    
    code-fold: true

editor: visual

