project:
  type: website
  resources: 
    -"*.jpeg"
  
website:
  title: "Kwiz Research"
  page-navigation: true
  cookie-consent: false
  
  search: 
    location: navbar
    type: textbox
    
  page-footer: 
    background: "#343434"
    foreground: rgba(300, 200, 100, 1)
    
    left: '&#169;2023: Kwiz Research, Built in R with Quarto'
    right: 
      - icon: github
        href: https://github.com/Kwiz-Research-Services
      - icon: linkedin
        href: https://www.linkedin.com/company/kwizresearch/

  navbar:
    foreground: rgba(300, 200, 100, 10)
    logo: images/krs_logo_4.png
    
    right:
      - index.qmd
      - about.qmd
      - text: "Services"
        menu: 
          - data.qmd
          - research.qmd
          - training.qmd
      - text: "Demos"
        menu: 
          - business_dashboard.qmd
          - mapping_dashboard.qmd
          - survival_dashboard.qmd
        

format:
  html:
    theme: sandstone
    backgroundcolor: rgba(166, 145, 92, 0.1);
    mainfont: Comic Sans MS
    fontcolor: black
    linkcolor: rgba(166, 145, 92, 1)
    
    page-layout: full
    css: styles.css
    toc: false

editor: visual

