project:
  type: website
  resources: 
    -"*.jpeg"
  
website:
  title: "Kwiz Research Services"
  page-navigation: true
  cookie-consent: false
  type: implied
  palette: light
  
  search: 
    location: navbar
    type: textbox
    
  page-footer: 
    left: '&#169;2022: Kwiz Research Services, Built with Quarto'
    right: 
      - icon: github
        href: https://github.com/Kwiz-Research-Services
      - icon: linkedin
        href: https://www.linkedin.com/company/kwizresearch/

  navbar:
    background: rgba(166, 145, 92, 1)
    
    right:
      - index.qmd
      - about.qmd
      - text: "Services"
        menu: 
          - data.qmd
          - research.qmd
      - text: "Demos"
        menu: 
          - business_dashboard.qmd
          - mapping_dashboard.qmd
          - survival_dashboard.qmd
        

format:
  html:
    backgroundcolor: white
    mainfont: cursive
    fontcolor: black
    linkcolor: rgba(166, 145, 92, 1)
    
    page-layout: full
    css: styles.css
    toc: false

editor: visual

