project:
  type: website
  resources: 
    -"*.jpeg"
  
website:
  title: "Kwiz Computing Technologies Limited"
  page-navigation: true
  cookie-consent: true
  
  navbar:
    foreground: "#1c4c9c"
    logo: 'images/Kwiz Main Logo 2400x1800.jpg'
    logo-alt: "Kwiz Computing Technologies Limited"

    
    right:
      - text: "Home"
        href: index.qmd
        
      - text: "Resource Centre"
        href: index_archive.qmd
      
      - text: "Play"
        menu: 
          - business_dashboard.qmd
          - mapping_dashboard.qmd
          - survival_dashboard.qmd
  
  search: 
    location: navbar
    type: textbox
    
  page-footer: 
    background: "#ad9882"
    foreground: "#1c4c9c"
    
    left: '&#169;2023: Kwiz Computing Technologies Limited'
    right: 
      - icon: github
        href: https://github.com/Kwiz-Computing-Technologies-Limited
      - icon: linkedin
        href: https://www.linkedin.com/company/kwizresearch/

  
        

format:
  html:
    theme: sandstone
    backgroundcolor: "#ffffff"
    mainfont: Black Street
    fontcolor: black
    linkcolor: "#104898"
    
    page-layout: full
    css: styles.css
    toc: false
    
    code-fold: true

editor: visual

