---
title: ""
geometry:
  - showframe
editor: 
  markdown: 
    wrap: 72
---

<!-- Sendinblue Conversations {literal} -->
<script>
    (function(d, w, c) {
        w.SibConversationsID = '643fda89e758061ca338bf4f';
        w[c] = w[c] || function() {
            (w[c].q = w[c].q || []).push(arguments);
        };
        var s = d.createElement('script');
        s.async = true;
        s.src = 'https://conversations-widget.sendinblue.com/sib-conversations.js';
        if (d.head) d.head.appendChild(s);
    })(document, window, 'SibConversations');
</script>
<!-- /Sendinblue Conversations {/literal} -->


```{r, echo=FALSE}
#| context: server-start
#| echo: false
library(shiny)
```

```{r, echo=FALSE}
#| context: server
#| eval: true
user_name = textInput("user_email", strong("Email"), placeholder = "example@gmail.com",
                      width = "40%")
user_query = textInput("user_query", strong("Lets talk"), placeholder = "start typing ...",
                       width = "100%")
```

::: rows
::: {.row width="10%"}
`r # user_name`
:::
::: {.row width="40%"}
`r # user_query`
:::
:::

